---
name: container

on:
  push:
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor:
          - base
          - shoelaces
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GCHR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          target: "${{ matrix.flavor }}"
          tags: "ghcr.io/${{ github.repository }}:${{ matrix.flavor }}-${{ env.RELEASE_VERSION }}"
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
